### ISSUE TITLE
Error with ImpromptuInterface

### ISSUE THREAD

**Issue by raghur** [roslynpad/roslynpad#295]
```
#r "nuget:Dynamitey/2.0.9.136"
#r "nuget:ImpromptuInterface/7.0.1"

using ImpromptuInterface;

public interface MyInterface {
    string Id {get;}
    DateTime Timestamp {get;}
    }
    
var s = new {
    Id = "123",
    Timestamp = DateTime.Now
    };
var o = Impromptu.ActLike<MyInterface>(s);
```

Get this error
```
Type 'ActLike_MyInterface_c3fbee3f231d4834bb1453624d5e06f0' from assembly 'ImpromptuInterfaceDynamicAssembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is attempting to implement an inaccessible interface.


   at System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
   at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.TypeBuilder.CreateTypeInfo()
   at ImpromptuInterface.Build.BuildProxy.BuildTypeHelper(ModuleBuilder builder, Type contextType, Type[] interfaces)
   at ImpromptuInterface.Build.BuildProxy.BuildType(Type contextType, Type mainInterface, Type[] otherInterfaces)
   at ImpromptuInterface.Impromptu.ActLike[TInterface](Object originalDynamic, Type[] otherInterfaces)
   at async Program.<Initialize>(?) in :line 15
   at Program.<Main>()
```

**Comment by Kirides** [comment]
This is the same issue as #275 the `public interface MyInterface` is contained in `private class Program` which means that a dynamically generated assembly can not implement `MyInterface`

**Comment by aelij** [comment]
This is now working when using the .cs mode (still not working in .csx)
