### ISSUE TITLE
FileNotFoundException for Microsoft.CSharp.dll

### ISSUE THREAD

**Issue by stanac** [roslynpad/roslynpad#456]
**Describe the bug**
After updating Visual Studio (not sure if related) RoslynPad reports error on start. Run (green play button) is disabled.

**To Reproduce**
Not sure how to reproduce it, it looks like it's environment specific.

**Expected behavior**
It's expected RoslynPad to start without errors.

**Version**
- OS: Windows 11
- Build (or commit ID if built from source): v17 from Windows Store

Exception:
```
System.IO.FileNotFoundException: Could not find a part of the path 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.0\ref\net7.0\Microsoft.CSharp.dll'.
File name: 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.0\ref\net7.0\Microsoft.CSharp.dll'
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\7.0.0\ref\net7.0\Microsoft.CSharp.dll'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Roslyn.Utilities.StandardFileSystem.OpenFile(String filePath, FileMode mode, FileAccess access, FileShare share)
   at Roslyn.Utilities.CommonCompilerFileSystemExtensions.OpenFileWithNormalizedException(ICommonCompilerFileSystem fileSystem, String filePath, FileMode fileMode, FileAccess fileAccess, FileShare fileShare)
   at Roslyn.Utilities.CommonCompilerFileSystemExtensions.OpenFileWithNormalizedException(ICommonCompilerFileSystem fileSystem, String filePath, FileMode fileMode, FileAccess fileAccess, FileShare fileShare)
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(String path, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at RoslynPad.Roslyn.RoslynHost.CreateMetadataReference(String location) in C:\src\github\aelij\RoslynPad\src\RoslynPad.Roslyn\RoslynHost.cs:line 109
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToArray()
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at RoslynPad.Build.ExecutionHost.<>c__DisplayClass106_0.<<RestoreAsync>g__ReadReferencesAsync|2>d.MoveNext() in C:\src\github\aelij\RoslynPad\src\RoslynPad.Build\ExecutionHost.cs:line 742
--- End of stack trace from previous location ---
   at RoslynPad.Build.ExecutionHost.<>c__DisplayClass106_0.<<RestoreAsync>g__DoRestoreAsync|0>d.MoveNext() in C:\src\github\aelij\RoslynPad\src\RoslynPad.Build\ExecutionHost.cs:line 710
```

`dotnet` from command line works as expected (`dotnet build`, `dotnet run`)

![image](https://user-images.githubusercontent.com/8450675/216978798-acd0bde0-c799-4801-8423-bb8baff6bc30.png)

**Comment by stanac** [comment]
Reinstalling the app from Microsoft Store didn't help.

I have downloaded and run main branch without issues. Not sure if it's helpful, but I have a workaround.
