### ISSUE TITLE
Improve error when .NET SDK isn't installed

### ISSUE THREAD

**Issue by Pxtl** [roslynpad/roslynpad#459]
Using RoslynPad 17.

Play and Stop buttons are greyed out, I can't do anything.  Just installed.  Used to use an older version a long time ago, used to work.

```
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at RoslynPad.Build.ProcessUtil.RunProcessAsync(String path, String workingDirectory, String arguments, CancellationToken cancellationToken) in C:\src\github\aelij\RoslynPad\src\RoslynPad.Build\ProcessUtil.cs:line 42
   at RoslynPad.Build.ExecutionHost.<>c__DisplayClass106_0.<<RestoreAsync>g__DoRestoreAsync|0>d.MoveNext() in C:\src\github\aelij\RoslynPad\src\RoslynPad.Build\ExecutionHost.cs:line 670
```

![image](https://user-images.githubusercontent.com/5386926/221284366-5abed167-9d69-4e02-b85b-2f00da71a019.png)

**Comment by aelij** [comment]
@Pxtl do you have a .NET 6+ **SDK** installed?
What's in the platforms dropdown in RoslynPad (where it says **.NET Framework x86**)?

**Comment by Pxtl** [comment]
@aelij 

![image](https://user-images.githubusercontent.com/5386926/235966248-2e480c5f-20c2-4f7a-abe1-7c4e87106203.png)

.NET Framework x64 and .NET Framework x86.  Neither work.

**Comment by aelij** [comment]
@Pxtl RoslynPad requires .NET 6+ SDK to work (even if you are targeting .NET Framework).
I do need to work on a better error.

**Comment by HoboCY** [comment]
> @Pxtl RoslynPad requires .NET 6+ SDK to work (even if you are targeting .NET Framework). RoslynPad 需要.NET6 + SDK 才能工作(即使你的目标是.NETFramework)。 I do need to work on a better error. 我确实需要改正一个更好的错误。
I always have the.net6-7 sdk installed on my computer

**Comment by Naomitr0n** [comment]
@aelij
Seems this problem came back. "Restore Error" is what shows with an SDK not installed on Win11 x64. Had to find this issue to figure out what was going on. Was the above commit by [ssaattww](https://github.com/ssaattww) undone somehow?

**Comment by aelij** [comment]
@Naomitr0n which version are you using?

**Comment by Naomitr0n** [comment]
Latest version installed through Microsoft Store
