### ISSUE TITLE
ArgumentOutOfRangeException in EditorOnToolTipRequest

### ISSUE THREAD

**Issue by 0x18C95** [roslynpad/roslynpad#466]
**Describe the bug**
Exception raised at TextMarkerService > EditorOnToolTipRequest(object? sender, ToolTipRequestEventArgs args) when mouse is hovered above the code.

**To Reproduce**
The Document property of the RoslynCodeEditor control is binded and the same is populated as:

this.Document.Text = PopulateCode();  //PopulateCode is some code snippets

>>When the application is initialized and mouse is hovered over the populated code, an exception is raised when mouse hits the "." between the codes, or space between the codes.

Attached screen shot for details

**Version**
- OS: Windows 11
- Build (or commit ID if built from source): 4.4.0
![RoslynPad](https://user-images.githubusercontent.com/131697707/234084094-0fd5db6b-0968-4e52-8d93-5b0d1fb4b996.gif)

**Comment by aelij** [comment]
Hey, thanks for the GIF! But can you please post the full stack trace as text? ;)

**Comment by 0x18C95** [comment]
Sure, heres the stack trace

   at ICSharpCode.AvalonEdit.Document.TextDocument.GetLineByNumber(Int32 number)
   at ICSharpCode.AvalonEdit.Document.TextDocument.GetOffset(Int32 line, Int32 column)
   at ICSharpCode.AvalonEdit.Document.TextDocument.GetOffset(TextLocation location)
   at RoslynPad.Editor.TextMarkerService.EditorOnToolTipRequest(Object sender, ToolTipRequestEventArgs args) in C:\Users\Joydeep\source\repos\roslynpad-17\src\RoslynPad.Editor.Shared\TextMarkerService.cs:line 62
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

Thanks for the lovely project. Much appreciated.

**Comment by aelij** [comment]
Fixed in c217452b457e3d888cf99c5dc8f81879d045c3bc
