### ISSUE TITLE
Add `/usr/lib64/dotnet` to .NET lookup in `PlatformsFactory`

### ISSUE THREAD

**Issue by terminal-root** [roslynpad/roslynpad#470]
When I run `dotnet RoslynPad.dll` the following exception is thrown after briefly showing a large white window with a single "Documents" widget.

```text
❯ dotnet RoslynPad.dll
Unhandled exception. System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at RoslynPad.UI.OpenDocumentViewModel.set_Platform(ExecutionPlatform value) in C:\src\github\aelij\RoslynPad\src\RoslynPad.Common.UI\ViewModels\OpenDocumentViewModel.cs:line 437
   at RoslynPad.UI.OpenDocumentViewModel.Initialize(DocumentId documentId, Action`1 onError, Func`1 getSelection, IDisposable viewDisposable) in C:\src\github\aelij\RoslynPad\src\RoslynPad.Common.UI\ViewModels\OpenDocumentViewModel.cs:line 596
   at RoslynPad.DocumentView.OnDataContextChanged(Object sender, EventArgs args) in C:\src\github\aelij\RoslynPad\src\RoslynPad.Avalonia\DocumentView.axaml.cs:line 61
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.JobRunner.JobWithArg.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 241
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.X11.X11PlatformThreading.CheckSignaled() in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 164
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 244
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at RoslynPad.Program.Main(String[] args) in C:\src\github\aelij\RoslynPad\src\RoslynPad.Avalonia\Program.cs:line 13
```
```
OS: Fedora Linux 37 (Xfce) x86_64 
Kernel: 6.2.12-200.fc37.x86_64 
DE: Xfce 4.16 
WM: Xfwm4 
```
```
❯ dotnet --version
7.0.105
```

**Comment by aelij** [comment]
Hey, can you please run `dotnet --info`?

**Comment by terminal-root** [comment]
@aelij 

```
❯ dotnet --info
.NET SDK:
 Version:   7.0.105
 Commit:    e1bc5e001c

Runtime Environment:
 OS Name:     fedora
 OS Version:  37
 OS Platform: Linux
 RID:         fedora.37-x64
 Base Path:   /usr/lib64/dotnet/sdk/7.0.105/

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  7.0.105 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.5 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib64/dotnet]

global.json file:
  Not found
```
