### ISSUE TITLE
RoslyPad 20 issues FileNotFoundException about missing msbuild.binlog when using .NET Framework x64

### ISSUE THREAD

**Issue by m-4-f** [roslynpad/roslynpad#569]
**Describe the bug**
Running a simple 
Console.WriteLine("HelloWorld");
using .NET Framework x64 complains about missing msbuild.binlog file in build folder.
Running the same snippet using .NET 8.0.403 works well.

**To Reproduce**
- start provided binary (see Version)
- create new Program
- insert code snippet (see Description)
- select ".NET Framework x64"
- hit the Run button

**Expected behavior**
- "HelloWorld" in the Results view Value column

**Actual behavior**
System.IO.FileNotFoundException: Could not find file 'C:\Users\user\AppData\Local\Temp\roslynpad\build\1ae165c0dba44efc8723c2f4a64efb95\msbuild.binlog'.
File name: 'C:\Users\user\AppData\Local\Temp\roslynpad\build\1ae165c0dba44efc8723c2f4a64efb95\msbuild.binlog'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.Build.Logging.StructuredLogger.BinaryLog.ReadBuild(String filePath, Progress progress, ReaderSettings readerSettings) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLog.cs:line 37
   at RoslynPad.Build.ExecutionHost.CompileWithMsbuild(String path, Nullable`1 optimizationLevel, CancellationToken cancellationToken) in D:\src\gh\aelij\roslynpad\src\RoslynPad.Build\ExecutionHost.cs:line 295
   at RoslynPad.Build.ExecutionHost.ExecuteAsync(String path, Boolean disassemble, Nullable`1 optimizationLevel, CancellationToken cancellationToken) in D:\src\gh\aelij\roslynpad\src\RoslynPad.Build\ExecutionHost.cs:line 226
   at RoslynPad.UI.OpenDocumentViewModel.RunAsync() in D:\src\gh\aelij\roslynpad\src\RoslynPad.Common.UI\ViewModels\OpenDocumentViewModel.cs:line 688

**Version**
- OS: Windows 11 x64 22H2
- .NET Framework 4.8.1 x64 (4.8.9256.0)
- Build (or commit ID if built from source):
I downloaded precompiled roslypad 20 for windows x64 .zip file  (https://github.com/roslynpad/roslynpad/releases/download/20/RoslynPad-windows-x64.zip)
which should be made of https://github.com/roslynpad/roslynpad/commit/d7e03b0ea507f544df4df6ac5451a4f35f1164e2

**Comment by Lauschwi** [comment]
Me same Problem. Is there a workaround?

**Comment by xprzemekw** [comment]
I still use 19.1 because of this issue.
